### ISSUE TITLE
Compatibility for some mods

### ISSUE THREAD

**Issue by KMFrench1** [yurisuika/Blossom#1]
Can you please add compatibility for the following mods that add shears. Only vanilla shear can harvest the apples currently.

https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-fabric
https://www.curseforge.com/minecraft/mc-mods/simple-emerald-tools-fabric
https://www.curseforge.com/minecraft/mc-mods/vanilla-shears

**Comment by yurisuika** [comment]
I can add compatibility for the first two, but the third does not use the Fabric Shears tag that the others do. Will be in the next update.
