### ISSUE TITLE
[SUGGESTION] Not every oak tree should have a chance of generating as a flowering oak

### ISSUE THREAD

**Issue by Sunconure11** [yurisuika/Blossom#4]
Just what it says on the tin

if this is already the case, feel free to close this. I haven’t had a chance to play this mod yet due to 1.18.2’s release

**Comment by yurisuika** [comment]
Blossom does not change tree generation at all. Every oak tree is generated as normal. Instead, bees actively pollinate oak leaves to make them blossom into flowering oak leaves.
