### ISSUE TITLE
Modrinth Client Requirements Incorrect?

### ISSUE THREAD

**Issue by UntalentedAmateur** [yurisuika/Blossom#5]
I've installed Blossom 1.0.4 (fabric) on my managed server and then created a new world to get it to generate appropriately within the world chunks.

Following the guidance on the Modrinth page (https://modrinth.com/mod/blossom) for the mod, which states that it is Optional for clients, I leave it off the client side and try to connect to the server.  I can not connect, as the client does not have the Blossom mod.

Adding the mod to the client, as well as the server, makes things work.  Is there a configuration setting somewhere that leaves the client side installation optional, or should it be Required?

**Comment by yurisuika** [comment]
Nope it definitely is required on the client. I must have accidentally confused it with the mod Compost, which is optional on client but was set to required. Thanks!

**Comment by UntalentedAmateur** [comment]
Hi Yurisuika,

Thanks for the quick response.  I'd already marked it as Required in my own modlist, but I wanted to check I hadn't made some mistake with configuring it or had some odd mod conflict going on.

It's a wonderful mod, and I love the other stuff you've made for Minecraft as well!
