### ISSUE TITLE
Crashes on 1.19.3

### ISSUE THREAD

**Issue by TheButterbrotMan** [yurisuika/Blossom#6]
https://bytebin.lucko.me/6iLmI0IRPE

**Comment by ALainxD** [comment]
Happens on many different mods* not just Blossom, assume it's something broken with fabric itself so expect it to be fixed fast.
*Chisel Refabricated, Enhanced vertical slabs, every compat and more

**Comment by yurisuika** [comment]
Yes, I see that is the case. I have not touched any version since 1.19.2 yet, so I cannot say if this is an issue with FAPI or the mod. Anyways, I will look into it!

**Comment by yurisuika** [comment]
Alright everything should be fixed! They broke Registry into two classes and renamed some stuff and moved some packages. Nothing major!
